// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btjidasmmguxybaiixag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0amlkYXNtbWd1eHliYWlpeGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MTYxOTksImV4cCI6MjA2Nzk5MjE5OX0.Sp3Y_GBItY-_sqv7V3g3qVRjAqVwPMPGhM03WXsXaBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});